<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://servico.masterdicas.gilmariosoftware.com.br/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://mestredasdicas-gilserver.openshift.com" name="DicaWS" targetNamespace="http://servico.masterdicas.gilmariosoftware.com.br/">
  <wsdl:import location="http://localhost:8080/WebService-1.0-SNAPSHOT/DicaWS/DicaServico?wsdl=DicaServicoInterface.wsdl" namespace="http://mestredasdicas-gilserver.openshift.com">
    </wsdl:import>
  <wsdl:binding name="DicaWSSoapBinding" type="ns1:DicaServicoInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="AlterarDica">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="AlterarDica">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="AlterarDicaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="BuscarDicas">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="BuscarDicas">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="BuscarDicasResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="RemoverDica">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="RemoverDica">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="RemoverDicaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="AdicionarDica">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="AdicionarDica">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="AdicionarDicaResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="DicaWS">
    <wsdl:port binding="tns:DicaWSSoapBinding" name="DicaWSPort">
      <soap:address location="http://localhost:8080/WebService-1.0-SNAPSHOT/DicaWS/DicaServico"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>