<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://servico.masterdicas.gilmariosoftware.com.br/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://mestredasdicas-gilserver.openshift.com" name="TagWS" targetNamespace="http://servico.masterdicas.gilmariosoftware.com.br/">
  <wsdl:import location="http://localhost:8080/WebService-1.0-SNAPSHOT/TagWS/TagServico?wsdl=TagServicoInterface.wsdl" namespace="http://mestredasdicas-gilserver.openshift.com">
    </wsdl:import>
  <wsdl:binding name="TagWSSoapBinding" type="ns1:TagServicoInterface">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="AdicionarTag">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="AdicionarTag">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="AdicionarTagResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="RemoverTag">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="RemoverTag">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="RemoverTagResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="BuscarTags">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="BuscarTags">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="BuscarTagsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="FaultException">
        <soap:fault name="FaultException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TagWS">
    <wsdl:port binding="tns:TagWSSoapBinding" name="TagWSPort">
      <soap:address location="http://localhost:8080/WebService-1.0-SNAPSHOT/TagWS/TagServico"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>