package br.com.gilmariosoftware.masterdicas.servico.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 *
 */
@WebService(name = "DicaServicoInterface", targetNamespace = "http://mestredasdicas-gilserver.openshift.com")
public interface DicaServicoInterface {

    /**
     *
     * @param dica
     * @return returns br.com.gilmariosoftware.masterdicas.servico.cliente.Dica
     * @throws FaultException
     */
    @WebMethod(operationName = "AlterarDica")
    @WebResult(name = "dica")
    public Dica alterarDica(
            @WebParam(name = "dica") Dica dica)
            throws FaultException;

    /**
     *
     * @param titulo
     * @param tags
     * @return returns
     * br.com.gilmariosoftware.masterdicas.servico.cliente.ListaDeDicas
     * @throws FaultException
     */
    @WebMethod(operationName = "BuscarDicas")
    @WebResult(name = "dicas")
    public ListaDeDicas buscarDicas(
            @WebParam(name = "tags") List<Tag> tags,
            @WebParam(name = "titulo") String titulo)
            throws FaultException;

    /**
     *
     *
     * @return returns
     * br.com.gilmariosoftware.masterdicas.servico.cliente.ListaDeDicas
     * @throws FaultException
     */
    @WebMethod(operationName = "BuscarUltimasDicas")
    @WebResult(name = "dicas")
    public ListaDeDicas buscarUltimasDicas() throws FaultException;

    /**
     *
     * @param nome
     * @return returns
     * br.com.gilmariosoftware.masterdicas.servico.cliente.ListaDeTags
     * @throws FaultException
     */
    @WebMethod(operationName = "BuscarTags")
    @WebResult(name = "tags")
    public ListaDeTags buscarTags(
            @WebParam(name = "nome") String nome)
            throws FaultException;

    /**
     *
     * @param removerDica
     * @return returns java.lang.String
     * @throws FaultException
     */
    @WebMethod(operationName = "RemoverDica")
    @WebResult(name = "informacao")
    public String removerDica(
            @WebParam(name = "RemoverDica") Dica removerDica)
            throws FaultException;

    /**
     *
     * @param removerTag
     * @return returns java.lang.String
     * @throws FaultException
     */
    @WebMethod(operationName = "RemoverTag")
    @WebResult(name = "informacao")
    public String removerTag(
            @WebParam(name = "RemoverTag") Tag removerTag)
            throws FaultException;

    /**
     *
     * @param dica
     * @return returns br.com.gilmariosoftware.masterdicas.servico.cliente.Dica
     * @throws FaultException
     */
    @WebMethod(operationName = "AdicionarDica")
    @WebResult(name = "dica")
    public Dica adicionarDica(
            @WebParam(name = "dica") Dica dica)
            throws FaultException;

    /**
     *
     * @param tag
     * @return returns br.com.gilmariosoftware.masterdicas.servico.cliente.Tag
     * @throws FaultException
     */
    @WebMethod(operationName = "AdicionarTag")
    @WebResult(name = "tag")
    public Tag adicionarTag(
            @WebParam(name = "tag") Tag tag)
            throws FaultException;

    /**
     *
     * @param nome
     * @param inicio
     * @param quantidade
     * @return
     * @throws FaultException
     */
    @WebMethod(operationName = "PaginarTags")
    @WebResult(name = "tags")
    public ListaDeTags paginarTags(
            @WebParam(name = "nome") String nome, @WebParam(name = "inicio") int inicio, @WebParam(name = "quantidade") int quantidade)
            throws FaultException;

    /**
     *
     * @param nome
     * @return
     * @throws FaultException
     */
    @WebMethod(operationName = "TotalTags")
    @WebResult(name = "total")
    public Long totalTags(
            @WebParam(name = "nome") String nome)
            throws FaultException;

}
