package br.com.gilmariosoftware.masterdicas.servico.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 *
 */
@WebServiceClient(name = "DicaWS", targetNamespace = "http://servico.masterdicas.gilmariosoftware.com.br/")
public class DicaWS
        extends Service {

    private final static URL DICAWS_WSDL_LOCATION;
    private final static WebServiceException DICAWS_EXCEPTION;
    private final static QName DICAWS_QNAME = new QName("http://servico.masterdicas.gilmariosoftware.com.br/", "DicaWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebService-1.0-SNAPSHOT/DicaWS/DicaServico?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DICAWS_WSDL_LOCATION = url;
        DICAWS_EXCEPTION = e;
    }

    public DicaWS() {
        super(__getWsdlLocation(), DICAWS_QNAME);
    }

    public DicaWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), DICAWS_QNAME, features);
    }

    public DicaWS(URL wsdlLocation) {
        super(wsdlLocation, DICAWS_QNAME);
    }

    public DicaWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DICAWS_QNAME, features);
    }

    public DicaWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DicaWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns DicaServicoInterface
     */
    @WebEndpoint(name = "DicaWSPort")
    public DicaServicoInterface getDicaWSPort() {
        return super.getPort(new QName("http://servico.masterdicas.gilmariosoftware.com.br/", "DicaWSPort"), DicaServicoInterface.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns DicaServicoInterface
     */
    @WebEndpoint(name = "DicaWSPort")
    public DicaServicoInterface getDicaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.masterdicas.gilmariosoftware.com.br/", "DicaWSPort"), DicaServicoInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DICAWS_EXCEPTION != null) {
            throw DICAWS_EXCEPTION;
        }
        return DICAWS_WSDL_LOCATION;
    }

}
