package br.com.gilmariosoftware.masterdicas.servico.cliente;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 *
 */
@WebService(name = "DicaServicoInterface", targetNamespace = "http://mestredasdicas-gilserver.openshift.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DicaServicoInterface {

    /**
     *
     * @param arg0
     * @return returns br.com.gilmariosoftware.masterdicas.servico.cliente.Dica
     * @throws FaultException
     */
    @WebMethod(operationName = "AlterarDica")
    @WebResult(name = "dica", targetNamespace = "")
    @RequestWrapper(localName = "AlterarDica", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.AlterarDica")
    @ResponseWrapper(localName = "AlterarDicaResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.AlterarDicaResponse")
    public Dica alterarDica(
            @WebParam(name = "arg0", targetNamespace = "") Dica arg0)
            throws FaultException;

    /**
     *
     * @param titulo
     * @param tags
     * @return returns
     * br.com.gilmariosoftware.masterdicas.servico.cliente.ListaDeDicas
     * @throws FaultException
     */
    @WebMethod(operationName = "BuscarDicas")
    @WebResult(name = "dicas", targetNamespace = "")
    @RequestWrapper(localName = "BuscarDicas", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.BuscarDicas")
    @ResponseWrapper(localName = "BuscarDicasResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.BuscarDicasResponse")
    public ListaDeDicas buscarDicas(
            @WebParam(name = "tags", targetNamespace = "") List<Tag> tags,
            @WebParam(name = "titulo", targetNamespace = "") String titulo)
            throws FaultException;

    /**
     *
     * @param nome
     * @return returns
     * br.com.gilmariosoftware.masterdicas.servico.cliente.ListaDeTags
     * @throws FaultException
     */
    @WebMethod(operationName = "BuscarTags")
    @WebResult(name = "tags", targetNamespace = "")
    @RequestWrapper(localName = "BuscarTags", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.BuscarTags")
    @ResponseWrapper(localName = "BuscarTagsResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.BuscarTagsResponse")
    public ListaDeTags buscarTags(
            @WebParam(name = "nome", targetNamespace = "") String nome)
            throws FaultException;

    /**
     *
     * @param removerDica
     * @return returns java.lang.String
     * @throws FaultException
     */
    @WebMethod(operationName = "RemoverDica")
    @WebResult(name = "informacao", targetNamespace = "")
    @RequestWrapper(localName = "RemoverDica", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.RemoverDica")
    @ResponseWrapper(localName = "RemoverDicaResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.RemoverDicaResponse")
    public String removerDica(
            @WebParam(name = "RemoverDica", targetNamespace = "") Dica removerDica)
            throws FaultException;

    /**
     *
     * @param removerTag
     * @return returns java.lang.String
     * @throws FaultException
     */
    @WebMethod(operationName = "RemoverTag")
    @WebResult(name = "informacao", targetNamespace = "")
    @RequestWrapper(localName = "RemoverTag", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.RemoverTag")
    @ResponseWrapper(localName = "RemoverTagResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.RemoverTagResponse")
    public String removerTag(
            @WebParam(name = "RemoverTag", targetNamespace = "") Tag removerTag)
            throws FaultException;

    /**
     *
     * @param arg0
     * @return returns br.com.gilmariosoftware.masterdicas.servico.cliente.Dica
     * @throws FaultException
     */
    @WebMethod(operationName = "AdicionarDica")
    @WebResult(name = "dica", targetNamespace = "")
    @RequestWrapper(localName = "AdicionarDica", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.AdicionarDica")
    @ResponseWrapper(localName = "AdicionarDicaResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.AdicionarDicaResponse")
    public Dica adicionarDica(
            @WebParam(name = "arg0", targetNamespace = "") Dica arg0)
            throws FaultException;

    /**
     *
     * @param tag
     * @return returns br.com.gilmariosoftware.masterdicas.servico.cliente.Tag
     * @throws FaultException
     */
    @WebMethod(operationName = "AdicionarTag")
    @WebResult(name = "tag", targetNamespace = "")
    @RequestWrapper(localName = "AdicionarTag", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.AdicionarTag")
    @ResponseWrapper(localName = "AdicionarTagResponse", targetNamespace = "http://mestredasdicas-gilserver.openshift.com", className = "br.com.gilmariosoftware.masterdicas.servico.cliente.AdicionarTagResponse")
    public Tag adicionarTag(
            @WebParam(name = "tag", targetNamespace = "") Tag tag)
            throws FaultException;

}
